export const getInputText = (state) => state.ListStore.InputText;
export const getLists = (state) => state.ListStore.Lists;
export const getShowLists = (state) => state.ListStore.ShowLists;
export const getFilter = (state) => state.ListStore.Filter;
export const getItemLeft = (state) => state.ListStore.ItemLeft;
export const getInputMin = (state) => state.ListStore.InputMin;
export const getInputSec = (state) => state.ListStore.InputSec;
export const getMinutes = (state) => state.ListStore.Minutes;
export const getSeconds = (state) => state.ListStore.Seconds;
